-- ThumbFetch Supabase schema
-- Run this once in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.thumbnail_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  video_url text not null,
  platform text not null,
  title text,
  thumbnail_url text not null,
  created_at timestamptz not null default now()
);

create index if not exists thumbnail_history_user_created_idx
  on public.thumbnail_history(user_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.thumbnail_history enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
  on public.profiles for select
  to authenticated
  using (id = auth.uid());

drop policy if exists "Users can read own history" on public.thumbnail_history;
create policy "Users can read own history"
  on public.thumbnail_history for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "Users can insert own history" on public.thumbnail_history;
create policy "Users can insert own history"
  on public.thumbnail_history for insert
  to authenticated
  with check (user_id = auth.uid());

grant select on public.profiles to authenticated;
grant select, insert on public.thumbnail_history to authenticated;
grant all on public.profiles to service_role;
grant all on public.thumbnail_history to service_role;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(coalesce(new.email,''), '@', 1))
  )
  on conflict (id) do update
    set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- After creating your own account, promote it to admin with:
-- update public.profiles set role = 'admin' where email = 'YOUR-EMAIL@example.com';
