-- MarketHub production test schema: Auth + Ads + Storage + Realtime Chat
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'User',
  email text,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.ads (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text default '',
  category text not null,
  price numeric(12,2) not null check (price >= 0),
  location text not null default 'India',
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ads_created_idx on public.ads(created_at desc);
create index if not exists ads_seller_idx on public.ads(seller_id);
create index if not exists ads_category_idx on public.ads(category);

create table if not exists public.favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  ad_id uuid not null references public.ads(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id, ad_id)
);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  ad_id uuid not null references public.ads(id) on delete cascade,
  buyer_id uuid not null references auth.users(id) on delete cascade,
  seller_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(ad_id,buyer_id,seller_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 2000),
  created_at timestamptz not null default now()
);
create index if not exists messages_conv_idx on public.messages(conversation_id,created_at);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public
as $$ begin
  insert into public.profiles(id,display_name,email)
  values(new.id,coalesce(new.raw_user_meta_data->>'display_name','User'),new.email)
  on conflict(id) do update set email=excluded.email;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.ads enable row level security;
alter table public.favorites enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;

drop policy if exists "public profiles read" on public.profiles;
create policy "public profiles read" on public.profiles for select using (true);
drop policy if exists "own profile update" on public.profiles;
create policy "own profile update" on public.profiles for update to authenticated using (id=auth.uid()) with check (id=auth.uid());

drop policy if exists "public ads read" on public.ads;
create policy "public ads read" on public.ads for select using (true);
drop policy if exists "users create ads" on public.ads;
create policy "users create ads" on public.ads for insert to authenticated with check (seller_id=auth.uid());
drop policy if exists "owners update ads" on public.ads;
create policy "owners update ads" on public.ads for update to authenticated using (seller_id=auth.uid()) with check (seller_id=auth.uid());
drop policy if exists "owners delete ads" on public.ads;
create policy "owners delete ads" on public.ads for delete to authenticated using (seller_id=auth.uid());

drop policy if exists "own favorites" on public.favorites;
create policy "own favorites" on public.favorites for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());

drop policy if exists "participants read conversations" on public.conversations;
create policy "participants read conversations" on public.conversations for select to authenticated using (buyer_id=auth.uid() or seller_id=auth.uid());
drop policy if exists "buyers create conversations" on public.conversations;
create policy "buyers create conversations" on public.conversations for insert to authenticated with check (buyer_id=auth.uid());

drop policy if exists "participants read messages" on public.messages;
create policy "participants read messages" on public.messages for select to authenticated using (
  exists(select 1 from public.conversations c where c.id=conversation_id and (c.buyer_id=auth.uid() or c.seller_id=auth.uid()))
);
drop policy if exists "participants send messages" on public.messages;
create policy "participants send messages" on public.messages for insert to authenticated with check (
  sender_id=auth.uid() and exists(select 1 from public.conversations c where c.id=conversation_id and (c.buyer_id=auth.uid() or c.seller_id=auth.uid()))
);

grant select on public.ads, public.profiles to anon, authenticated;
grant insert,update,delete on public.ads to authenticated;
grant select,insert,update,delete on public.favorites to authenticated;
grant select,insert on public.conversations to authenticated;
grant select,insert on public.messages to authenticated;
grant usage,select on sequence public.messages_id_seq to authenticated;

-- Storage bucket for listing photos
insert into storage.buckets(id,name,public) values('listing-images','listing-images',true)
on conflict(id) do update set public=true;

drop policy if exists "public listing images read" on storage.objects;
create policy "public listing images read" on storage.objects for select using (bucket_id='listing-images');
drop policy if exists "users upload listing images" on storage.objects;
create policy "users upload listing images" on storage.objects for insert to authenticated
with check (bucket_id='listing-images' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists "users update own listing images" on storage.objects;
create policy "users update own listing images" on storage.objects for update to authenticated
using (bucket_id='listing-images' and owner_id=auth.uid()::text);
drop policy if exists "users delete own listing images" on storage.objects;
create policy "users delete own listing images" on storage.objects for delete to authenticated
using (bucket_id='listing-images' and owner_id=auth.uid()::text);

-- Enable Realtime for chat messages (safe to run more than once)
do $
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;
end $;
