create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,email text unique,display_name text,role text not null default 'user' check(role in ('user','admin')),created_at timestamptz default now());
create table if not exists public.ads(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,title text not null,description text,category text not null,price numeric(14,2) not null check(price>=0),location text not null,image_url text,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.favorites(user_id uuid references public.profiles(id) on delete cascade,ad_id uuid references public.ads(id) on delete cascade,created_at timestamptz default now(),primary key(user_id,ad_id));
create table if not exists public.messages(id bigint generated always as identity primary key,ad_id uuid references public.ads(id) on delete cascade,sender_id uuid references public.profiles(id) on delete cascade,receiver_id uuid references public.profiles(id) on delete cascade,body text not null check(length(body)>0 and length(body)<=2000),created_at timestamptz default now());
alter table public.profiles enable row level security; alter table public.ads enable row level security; alter table public.favorites enable row level security; alter table public.messages enable row level security;
create or replace function public.handle_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,email,display_name) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'display_name','User')) on conflict(id) do update set email=excluded.email; return new; end;$$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_user();
drop policy if exists "profiles own" on public.profiles; create policy "profiles own" on public.profiles for select to authenticated using(id=auth.uid());
drop policy if exists "ads public read" on public.ads; create policy "ads public read" on public.ads for select using(true);
drop policy if exists "ads own insert" on public.ads; create policy "ads own insert" on public.ads for insert to authenticated with check(user_id=auth.uid());
drop policy if exists "ads own update" on public.ads; create policy "ads own update" on public.ads for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists "ads own delete" on public.ads; create policy "ads own delete" on public.ads for delete to authenticated using(user_id=auth.uid());
drop policy if exists "fav own" on public.favorites; create policy "fav own" on public.favorites for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists "messages participants read" on public.messages; create policy "messages participants read" on public.messages for select to authenticated using(sender_id=auth.uid() or receiver_id=auth.uid());
drop policy if exists "messages sender insert" on public.messages; create policy "messages sender insert" on public.messages for insert to authenticated with check(sender_id=auth.uid());
grant select on public.ads to anon,authenticated; grant select on public.profiles to authenticated; grant all on public.ads,public.favorites,public.messages to authenticated;
insert into storage.buckets(id,name,public) values('listing-images','listing-images',true) on conflict(id) do nothing;
alter table public.messages replica identity full;
